name: agent-pr

on:
  workflow_dispatch:
    inputs:
      account_name:
        required: true
        type: string
      project_name:
        required: true
        type: string
      app_name:
        required: true
        type: string
      deployment_name:
        required: true
        type: string
      agent_definition:
        required: true
        type: string

permissions:
  contents: write
  pull-requests: write

jobs:
  create-pr:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - run: |
          BRANCH=feature/${{ github.event.inputs.app_name }}/${{ github.event.inputs.deployment_name }}-${{ github.run_id }}
          git checkout -b $BRANCH

          DIRECTORY=agents/${{ github.event.inputs.account_name }}/${{ github.event.inputs.project_name}}

          mkdir -p $DIRECTORY
          echo '${{ github.event.inputs.agent_definition }}' > $DIRECTORY/${{ github.event.inputs.app_name }}.json

          git config user.name bot
          git config user.email bot@users.noreply.github.com

          git add .
          git commit -m "Add agent"
          git push origin HEAD

      - run: |
          gh pr create \
            --title "Update agent ${{ github.event.inputs.app_name }}" \
            --body "Deployment: ${{ github.event.inputs.deployment_name }}"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
